version: '3'
services:
  nginx:
    build:
      context: back
      dockerfile: nginx.docker
    restart: always
    volumes:
      - ../back/:/app:ro
    environment:
      TZ: "Europe/Moscow"
    ports:
      - "8080:80"
    depends_on:
      - php-fpm
    networks:
      - network

  php-fpm:
    restart: always
    build:
      context: back
      dockerfile: php-fpm.docker
    user: "1000:1000"
    volumes:
      - ../back/:/app:rw
      - ./back/usr/local/etc/php/custom.d:/usr/local/etc/php/custom.d:ro
      - ./data/logs/php-fpm:/logs:rw
    expose:
      - 9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      TZ: "Europe/Moscow"
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
      PHP_IDE_CONFIG: serverName=docker-${COMPOSE_PROJECT_NAME}
      PHP_INI_SCAN_DIR: ":/usr/local/etc/php/custom.d"
    depends_on:
      - postgres
    networks:
      - network

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata:rw
      - ./backup:/backup:rw
    expose:
      - 5432
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - network

  frontend-nginx:
    build:
      context: front
      dockerfile: nginx.docker
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ../front/:/var/www/frontend
    ports:
      - "8081:80"
    depends_on:
      - php-fpm
    networks:
      - network


  frontend-nodejs:
    build:
      context: front
      dockerfile: node.docker
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ../front/:/var/www/frontend
    ports:
      - "8085:8080"
    working_dir: /var/www/frontend
    tty: true
    networks:
      - network

  adminer:
    image: adminer
    restart: always
    environment:
      TZ: "Europe/Moscow"
    expose:
      - 8080
    ports:
      - "8082:8080"
    networks:
      - network



networks:
  network:
    driver: bridge
    ipam:
      driver: default

